import Display from '@/lib/core/Display';
import { stageHeight, stageWidth } from '@/lib/utils/controls';

export default class QuantumNeuralWebDisplay extends Display {
  static config = {
    name: 'QuantumNeuralWebDisplay',
    description:
      'Dynamic floating particle constellation network. Audio frequencies modulate node sizes and send bright electrical synapses impulses traveling down web connections — perfect for brainwave entrainment, ambient, and lo-fi tracks.',
    type: 'display',
    label: 'Quantum Neural Web',
    defaultProperties: {
      particleCount: 100,
      connectDistance: 110,
      amplitude: 50,
      speed: 0.8,
      particleSize: 2.2,
      lineWidth: 1.0,
      lineOpacity: 0.2,
      color: '#00f3ff',
      glowColor: '#00f3ff',
      glowIntensity: 15,
      sensitivity: 1.2,
      pulseSpeed: 1.5,
      width: 854,
      height: 854,
      x: 0,
      y: 0,
      opacity: 1.0,
    },
    controls: {
      width: {
        label: 'Width',
        type: 'number',
        min: 100,
        max: 2000,
        step: 10,
        withRange: true,
      },
      height: {
        label: 'Height',
        type: 'number',
        min: 100,
        max: 2000,
        step: 10,
        withRange: true,
      },
      particleCount: {
        label: 'Particle Count',
        type: 'number',
        min: 20,
        max: 220,
        step: 5,
        withRange: true,
      },
      connectDistance: {
        label: 'Connection Range',
        type: 'number',
        min: 30,
        max: 250,
        step: 5,
        withRange: true,
      },
      amplitude: {
        label: 'Reactivity Size',
        type: 'number',
        min: 5,
        max: 150,
        step: 5,
        withRange: true,
      },
      speed: {
        label: 'Movement Speed',
        type: 'number',
        min: 0.1,
        max: 3.0,
        step: 0.1,
        withRange: true,
      },
      pulseSpeed: {
        label: 'Synapse Pulse Speed',
        type: 'number',
        min: 0.5,
        max: 4.0,
        step: 0.1,
        withRange: true,
      },
      particleSize: {
        label: 'Node Size',
        type: 'number',
        min: 1.0,
        max: 8.0,
        step: 0.5,
        withRange: true,
      },
      lineWidth: {
        label: 'Web Line Width',
        type: 'number',
        min: 0.5,
        max: 5.0,
        step: 0.5,
        withRange: true,
      },
      lineOpacity: {
        label: 'Web Line Opacity',
        type: 'number',
        min: 0.0,
        max: 1.0,
        step: 0.05,
        withRange: true,
      },
      color: {
        label: 'Node Color',
        type: 'color',
      },
      glowColor: {
        label: 'Glow Color',
        type: 'color',
      },
      glowIntensity: {
        label: 'Glow Intensity',
        type: 'number',
        min: 0,
        max: 40,
        step: 1,
        withRange: true,
      },
      sensitivity: {
        label: 'Audio Sensitivity',
        type: 'number',
        min: 0.2,
        max: 4.0,
        step: 0.1,
        withRange: true,
      },
      opacity: {
        label: 'Opacity',
        type: 'number',
        min: 0,
        max: 1.0,
        step: 0.01,
        withRange: true,
      },
      x: {
        label: 'X Offset',
        type: 'number',
        min: stageWidth(n => -n),
        max: stageWidth(),
        withRange: true,
        hideFill: true,
      },
      y: {
        label: 'Y Offset',
        type: 'number',
        min: stageHeight(n => -n),
        max: stageHeight(),
        withRange: true,
        hideFill: true,
      },
    },
  };

  constructor(properties?: Record<string, unknown>) {
    super(QuantumNeuralWebDisplay, properties);
  }
}
